# Generated by Django 6.0 on 2026-01-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='auther',
            new_name='author',
        ),
    ]
